"""new fields in comment model

Revision ID: 21b410db7636
Revises: 54a038e10727
Create Date: 2020-06-03 21:42:52.595427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b410db7636'
down_revision = '54a038e10727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
