"""new fields in user model

Revision ID: 2cafa6f25899
Revises: 63d5ebf81849
Create Date: 2020-04-14 12:43:30.893623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cafa6f25899'
down_revision = '63d5ebf81849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ava', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_user_ava'), 'user', ['ava'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ava'), table_name='user')
    op.drop_column('user', 'ava')
    # ### end Alembic commands ###
