"""empty message

Revision ID: 879597c3f060
Revises: 8927e589e728
Create Date: 2020-04-14 12:34:40.786128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879597c3f060'
down_revision = '8927e589e728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
