"""empty message

Revision ID: 8927e589e728
Revises: 139f974168fe
Create Date: 2020-04-14 12:27:16.390643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8927e589e728'
down_revision = '139f974168fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
