"""new fields in user model

Revision ID: 96482578d833
Revises: 879597c3f060
Create Date: 2020-04-14 12:40:08.031075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96482578d833'
down_revision = '879597c3f060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ava', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_user_ava'), 'user', ['ava'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ava'), table_name='user')
    op.drop_column('user', 'ava')
    # ### end Alembic commands ###
