"""new fields in user model

Revision ID: ecfb5ba71686
Revises: a4562c4b4abe
Create Date: 2020-04-14 12:13:03.678694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfb5ba71686'
down_revision = 'a4562c4b4abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_profile_picture'), 'user', ['profile_picture'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_picture'), table_name='user')
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###
